version: '3.4'

services:
  immersivepage:
    image: immersivepage
    build:
      context: .
      dockerfile: ./Dockerfile
    
    container_name: immersivepage-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm start

    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
